language: go
go: 
 - 1.8
services:
 -postgresql
before_script:
 - psql -c 'create database zedlist_test;' -U postgres
before_install:
 - go get -t -v ./...
 - go get github.com/mattn/goveralls
script:
 - go build ./cmd/zedlist
 - make test